[package]
name = "server"
version = "0.1.0"
authors = ["robeady <robertj.eady@gmail.com>"]
edition = "2018"

[dependencies]
rodio = "0.9.0"
actix-web = "1.0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
